language: node_js
node_js:
  - '10.16.3'
script:
  - npm run lint
  - npm run test:migration:undo
  - npm run test:migration:do
  - npm run test:seed:undo
  - npm run test:seed:do
  - npm run test
before_script:
  - npm install
after_success:
  - npm run test:coverage
  - npm run push:coveralls
