const Sequelize = require('sequelize');

let Table = Sequelize.Model;

exports.setTable=(table)=>{
    Table = table
}

exports.createSycn = (row) => {
    return new Promise((resolve, reject) => {
    Table.sync({ force: true }).then(() => {
        // Now the `users` table in the database corresponds to the model definition
        Table.create(row).then((createdRow) => {
            resolve(createdRow);
        }).catch((error)=>{
            reject(error)
        });
    })
})
}

exports.findAll = () => {
    return new Promise((resolve, reject) => {
        // Find all rows
        Table.findAll()
        .then(rows => {
             resolve(rows) })
        .catch((error) => {
             reject(error) });
    })
}

exports.create = (row) => {
    return new Promise((resolve, reject) => {
        // Create a new user return autogenerated id
        Table.create(row)
        .then((createdRow) => {
            resolve(createdRow);
        })
        .catch((error) => {
            reject(error);
        });
    })
}

exports.destroy = (rowId) => {
    return new Promise((resolve, reject) => {
    // Delete user with id
    Table.destroy({
        where: {
            id: rowId
        }
    }).then(() => {
        resolve(true);
    }).catch((error)=>{
        reject(error)
    });
})
}

exports.update = (row) => {
    return new Promise((resolve, reject) => {
        // Change data for user with id
        Table.update(row, {
            where: {
                id: row.id
            }
        }).then((updatedRows) => {
            resolve(updatedRows)
        }).catch((error) => { 
            reject(error) 
        });

    }
    )
}