class DbControlClass{

constructor(table) {
    this.Table = table;
}

    createSycn(row){
        return new Promise((resolve, reject) => {
            this.Table.sync({ force: true }).then(() => {
                // Now the `users` table in the database corresponds to the model definition
                this.Table.create(row).then((createdRow) => {
                    resolve(createdRow);
                }).catch((error) => {
                    reject(error)
                });
            })
        })
    }

    findAll(){
        return new Promise((resolve, reject) => {
            // Find all rows
            this.Table.findAll()
                .then(rows => {
                    resolve(rows)
                })
                .catch((error) => {
                    reject(error)
                });
        })
    }

    create(row){
        return new Promise((resolve, reject) => {
            // Create a new user return autogenerated id
            this.Table.create(row)
                .then((createdRow) => {
                    resolve(createdRow);
                })
                .catch((error) => {
                    reject(error);
                });
        })
    }

    destroy(rowId){
        return new Promise((resolve, reject) => {
            // Delete user with id
            this.Table.destroy({
                where: {
                    id: rowId
                }
            }).then(() => {
                resolve(true);
            }).catch((error) => {
                reject(error)
            });
        })
    }

    update(row){
        return new Promise((resolve, reject) => {
            // Change data for user with id
            this.Table.update(row, {
                where: {
                    id: row.id
                }
            }).then((updatedRows) => {
                resolve(updatedRows)
            }).catch((error) => {
                reject(error)
            });

        }
        )
    }

}

module.exports = DbControlClass;

