const User = require('../model/userModel');

exports.createSycn = (user)=> { 
    User.sync({ force: true }).then(() => {
        // Now the `users` table in the database corresponds to the model definition
        User.create(user).then(()=>{
            console.log("User Created");
        });
    })
}

exports.findAll = () => {return new Promise((resolve, reject) => { 
// Find all users
    User.findAll().then(users => { resolve(users)}).catch((error) => { reject(error)});
})}

exports.create = (user) => {
// Create a new user return autogenerated id
    User.create(user).then(me => {
    console.log("Auto-generated ID:", me.id);
});
}

exports.destroy = (userId) => {
// Delete user with id
User.destroy({
    where: {
        id: userId
    }
}).then(() => {
    console.log("Done");
});
}

exports.update = (user) => {
    return new Promise((resolve, reject) => {
// Change data for user with id
    User.update(user, {
    where: {
        id: user.id
    }
}).then((updatedRows) => {
    resolve(updatedRows)
}).catch((error)=>{reject(error)});

}
)
}